Models/Signin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Runtime.Remoting.Lifetime;

namespace Property_rental_management_system.Models
{
    public class Signin
    {
        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is required")]
        public string Username { get; set; }


        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required")]

        public string Password { get; set; }


       



    }
}

Models/Signup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Property_rental_management_system.Models
{
    public class Signup
    {
       
        public int Id { get; set; }


        [DisplayName("First name")]
        [Required(ErrorMessage ="First name is required")]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only alphabetic characters are allowed")]
        public string Firstname { get; set; }


        [DisplayName("Last name")]
        [Required(ErrorMessage = "Last name is required")]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "Only alphabetic characters are allowed")]
        public string Lastname { get; set; }


        [DisplayName("Date of birth")]
        [DataType(DataType.Date)] 
        [Required(ErrorMessage = "Date of birth is required")]
        public string Dateofbirth { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "Gender is required")]

        public string Gender { get; set; }


        [DisplayName("Phone number")]
        [Required(ErrorMessage = "Phone number is required")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone number must be exactly 10 digits")]
        public string Phonenumber { get; set; }


        [DisplayName("Email address")]
        [Required(ErrorMessage = "Email address is required")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email address")]
        public string Email { get; set; }


        [DisplayName("Address")]
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        [DisplayName("State")]
        [Required(ErrorMessage = "State is required")]
        public string State { get; set; }

        [DisplayName("City")]
        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }

        [DisplayName("Pincode")]
        [Required(ErrorMessage = "Pincode is required")]
        [RegularExpression(@"^\d{6}$", ErrorMessage = "Pincode must be a 6-digit number")]
        public string Pincode { get; set; }

        [DisplayName("Username")]
        [Required(ErrorMessage = "Username is required")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Please enter valid email format")]
        public string Username { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password is required")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,}$",
        ErrorMessage = "Password must contain at least one lowercase letter, one uppercase letter, one digit, and be at least 8 characters long.")]
        public string Password { get; set; }

        [DisplayName("Confirm password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please confirm your password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string Confirmpassword { get; set; }


    }
}

Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Property_rental_management_system.Models;
using Property_rental_management_system.Repository;
using System.IO;
using System.Web.Security;

namespace Property_rental_management_system.Controllers
{
    public class SignupController : Controller
    {
        private void LogError(string logFilePath, Exception ex)
        {
            using (StreamWriter writer = new StreamWriter(logFilePath, true))
            {
                writer.WriteLine("Error Date: " + DateTime.Now.ToString());
                writer.WriteLine("Message: " + ex.Message);
                writer.WriteLine("Stack Trace: " + ex.StackTrace);
                writer.WriteLine("--------------------------------------------------");
            }
        }
        string logFilePath = "C:\\Users\\HP\\source\\repos\\Property rental management system\\ErrorLog.txt";

        /// <summary>
        /// Sign up
        /// </summary>
        /// <returns></returns>
        [HttpGet]   
        public ActionResult AddDetails()
        {
            return View();
        }

        /// <summary>
        ///  POST: Signup/Create
        /// </summary>
        /// <param name="signup"></param>
        /// <returns></returns>
        [HttpPost]
         public ActionResult AddDetails(Signup signup)
         {
             try
             {
                 // TODO: Add insert logic here
                 if (ModelState.IsValid)
                 {
                     homepageRepository signupRepo = new homepageRepository();
                     if (signupRepo.AddDetails(signup))
                     {
                        TempData["SignupSuccessMessage"] = "Signup  successfull.Now Sign in please....! ";
                    }
                    else
                    {
                        TempData["SignupErrorMessage"] = "Unable to save user details.";

                    }
                }

                 return RedirectToAction("Signin");
             }
            catch (SqlException ex)
            {
                TempData["SignupErrorMessage"] = ex.Message; // Store the SQL error message
                LogError(logFilePath, ex);

                return View();

            }
            catch (Exception ex)
            {
                TempData["SignupErrorMessage"] = "An error occurred: " + ex.Message;
                LogError(logFilePath, ex);

                return View();
            }
        }


        [HttpGet]
        public ActionResult Signin()
        {
            return View();
        }
      
        /// <summary>
        /// Sign in page
        /// </summary>
        /// <param name="signin"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Signin(Signin signin)
        {
            try
            {
                homepageRepository repository = new homepageRepository();

                bool isValidUser = repository.Signin(signin);
                bool isValidAdmin = repository.SigninAdmin(signin);


                if (isValidUser)
                {
                    Session["username"] = signin.Username.ToString();
                    Session["password"] = signin.Password.ToString();
                    FormsAuthentication.SetAuthCookie(signin.Username, false);
                    Session["role"] = "User";
                    return RedirectToAction("UserIndex", "User");
                }
                else if (isValidAdmin)
                {
                    Session["username"] = signin.Username.ToString();
                    Session["password"] = signin.Password.ToString();
                    FormsAuthentication.SetAuthCookie(signin.Username, false);
                    Session["role"] = "Admin";
                    return RedirectToAction("AdminIndex", "Admin");
                }
                else
                {
                    ViewData["Message"] = "Invalid username or password";
                }

                return View(signin);
            }
            catch (Exception ex)
            {
                LogError(logFilePath, ex);
                throw;
            }
        }


        
    }
}

Views/Signup/AddDetails.cshtml
@model Property_rental_management_system.Models.Signup

@{
    ViewBag.Title = "AddDetails";
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/css/signup.css" rel="stylesheet" />
    <link href="~/Content/css/background.css" rel="stylesheet" />
</head>
<body>
    @if (TempData["SignupErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            <strong>Error!</strong> @TempData["SignupErrorMessage"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span>&times;</span>
            </button>
        </div>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <h2>Sign up</h2>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your first name" } })
                    @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your last name" } })
                    @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Dateofbirth, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Dateofbirth, new { htmlAttributes = new { @class = "form-control", max = new DateTime(2010, 12, 31).ToString("yyyy-MM-dd") } })
                    @Html.ValidationMessageFor(model => model.Dateofbirth, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.RadioButtonFor(model => model.Gender, "M")
                    @Html.Label("Male")
                    @Html.RadioButtonFor(model => model.Gender, "F")
                    @Html.Label("Female")

                    @Html.RadioButtonFor(model => model.Gender, "O")
                    @Html.Label("Other")

                </div>
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phonenumber, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phonenumber, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your Phone number" } })
                    @Html.ValidationMessageFor(model => model.Phonenumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your email address" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Address, new { cols = 50, htmlAttributes = new { @class = "form-control", placeholder = "Enter your email address" } })
                </div>
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("State", new List<SelectListItem>
         {
             new SelectListItem { Text = "Kerala", Value = "Kerala" },
             new SelectListItem { Text = "Tamil Nadu", Value = "Tamil Nadu" },
             new SelectListItem { Text = "Haryana", Value = "Haryana" },
             new SelectListItem { Text = "Goa", Value = "Goa" }
         }, "Select an option", new { @class = "form-control dropdown-white", @id = "state" })

                    @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("City", new List<SelectListItem>
         {
         }, "Select an option", new { @class = "form-control dropdown-white", @id = "city" })

                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Pincode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Pincode, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your pincode" } })
                    @Html.ValidationMessageFor(model => model.Pincode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your username" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Confirmpassword, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Confirmpassword, new { htmlAttributes = new { @class = "form-control", placeholder = "Confirm your password" } })
                    @Html.ValidationMessageFor(model => model.Confirmpassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Sign up" class="btn btn-info" />
                </div>
            </div>
        </div>

    }

    @section Scripts {
        <script src="~/Scripts/javascript/AutoHideAlert.js"></script>
        <script src="~/Scripts/javascript/Signup.js"></script>
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

Views/Signup/Signin.cshtml
@model Property_rental_management_system.Models.Signin

@{
    ViewBag.Title = "Signin";
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/css/signin.css" rel="stylesheet" />
    <link href="~/Content/css/background.css" rel="stylesheet" />
</head>
<body>
    @if (TempData["SignupSuccessMessage"] != null)
    {
        <div class="alert alert-success">
            <strong>Success ! </strong>@TempData["SignupSuccessMessage"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span>&times;</span>
            </button>
        </div>
    }

    else if (TempData["SignupErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            <strong>Error ! </strong>@TempData["SignupErrorMessage"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span>&times;</span>
            </button>
        </div>
    }
    else if (TempData["PasswordChangeMessage"] != null)
    {
        <div class="alert alert-success">
            <strong>Success ! </strong>@TempData["PasswordChangeMessage"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span>&times;</span>
            </button>
        </div>
    }
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h2>Sign in</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your username" } })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
                <small class="error-message" style="color:red;">@Html.ViewData["Message"]</small>

            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Sign in" class="btn btn-info" />
                </div>
            </div>

            <!--
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.ActionLink("Forgot Password?", "ForgotPassword", "Account")
                </div>
            </div>
            -->


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 not-a-member" style="color:white;">
                    Not yet a member? <a href="@Url.Action("AddDetails", "Signup")">Sign up</a>
                </div>
            </div>


        </div>
    }

    <div>
    </div>

    @section Scripts {
        <script src="~/Scripts/javascript/AutoHideAlert.js"></script>
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>
</html>

Views/Signup/UserProfile.cshtml
@model Property_rental_management_system.Models.Signup

@{
    ViewBag.Title = "UserProfile";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}

<h2>UserProfile</h2>
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        <strong>Error ! </strong>@TempData["ErrorMessage"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span>&times;</span>
        </button>
    </div>
}

<div>
    <h4>Signup</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lastname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lastname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dateofbirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dateofbirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phonenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phonenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pincode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pincode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>



    </dl>
</div>